services:
  client-adapter:
    build: .
    container_name: openbanking_client_adapter
    ports:
      - "4000:4000"
    environment:
      - CLIENT_ADAPTER_PORT=4000
      - HUB_URL=http://host.docker.internal:3000
    restart: always
