version: '3.8'

services:
  sdk-client:
    build: .
    container_name: ob_sdk_client
    ports:
      - "${CLIENT_ADAPTER_PORT:-4000}:${CLIENT_ADAPTER_PORT:-4000}"
    environment:
      CLIENT_ADAPTER_PORT: ${CLIENT_ADAPTER_PORT:-4000}
      HUB_URL: ${HUB_URL:-http://host.docker.internal:3000}
    restart: unless-stopped
